services:
  redis:
    image: redis

pipeline:
  test:
    image: node:7-alpine
    commands:
      - apk add --update redis
      - cat test/redis-data.txt | redis-cli --pipe
      - npm set progress=false
      - npm install
      - ./node_modules/.bin/mocha --debug
  build:
    image: docker
    commands:
      - docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD registry.online.ntnu.no
      - docker build -t registry.online.ntnu.no/dotkom/slackguru:latest -f Dockerfile .
      - docker push registry.online.ntnu.no/dotkom/slackguru:latest
    when:
      branch: master
      event: push
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  release:
    image: plugins/ssh
    host: vsop.online.ntnu.no
    port: 22
    user: root
    script:
      - systemctl restart slackguru.service
    when:
      branch: master
      event: push
